# Generated by Django 2.0 on 2018-02-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jacc', '0010_auto_20180201_0734'),
        ('jbank', '0016_auto_20180208_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutparty',
            name='payouts_account',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='jacc.AccountEntry', verbose_name='payouts account'),
        ),
    ]
