# Generated by Django 3.1 on 2020-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0003_auto_20200902_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="attachment",
            field=models.FileField(blank=True, upload_to="uploads", verbose_name="attachment"),
        ),
    ]
