# Generated by Django 3.1 on 2020-12-03 23:08

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0004_refund_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="payer_name",
            field=jutil.modelfields.SafeCharField(blank=True, db_index=True, default="", max_length=12, verbose_name="payer name"),
        ),
    ]
