# Generated by Django 3.1 on 2021-03-18 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0005_auto_20201203_2308"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="statementrecorddetail",
            options={"verbose_name": "statement record details", "verbose_name_plural": "statement record details"},
        ),
        migrations.AlterModelOptions(
            name="statementrecordremittanceinfo",
            options={
                "verbose_name": "statement record remittance info",
                "verbose_name_plural": "statement record remittance info",
            },
        ),
    ]
