# Generated by Django 3.2 on 2021-05-12 22:08

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0007_auto_20210507_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="receipt_code",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[("", ""), ("0", "(0)"), ("E", "Separate"), ("P", "Separate/Paper")],
                db_index=True,
                max_length=1,
                verbose_name="receipt code",
            ),
        ),
        migrations.AlterField(
            model_name="statementrecord",
            name="receipt_code",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[("", ""), ("0", "(0)"), ("E", "Separate"), ("P", "Separate/Paper")],
                db_index=True,
                max_length=1,
                verbose_name="receipt code",
            ),
        ),
    ]
