# Generated by Django 3.2.3 on 2021-05-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0008_auto_20210512_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepaymentbatchfile",
            name="cached_total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name="total amount"),
        ),
    ]
