# Generated by Django 3.2.3 on 2021-05-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0010_statementrecorddetail_creditor_account_scheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepaymentbatch",
            name="cached_total_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name="total amount"),
        ),
    ]
