# Generated by Django 3.2.9 on 2021-12-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0013_euriborrate"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutstatus",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True, verbose_name="timestamp"),
        ),
    ]
