# Generated by Django 3.2.9 on 2021-12-06 15:19

from django.db import migrations, models
import django.utils.timezone
from django.db.models import F


def migr_0016(apps, schema):
    PayoutStatus = apps.get_model("jbank", "PayoutStatus")
    PayoutStatus.objects.filter(timestamp=None).update(timestamp=F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0015_ps_timestamp_fill"),
    ]

    operations = [
        migrations.RunPython(migr_0016),
        migrations.AlterField(
            model_name="payoutstatus",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, editable=False, verbose_name="timestamp"),
        ),
    ]
