# Generated by Django 4.1.7 on 2023-02-25 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0021_alter_accountbalance_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountbalance",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="jbank.wsediconnection",
                verbose_name="WS-EDI connection",
            ),
        ),
    ]
