# Generated by Django 4.1.7 on 2023-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0023_remove_accountbalance_connection_accountbalance_bic"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepaymentbatchfile",
            name="additional_info",
            field=models.CharField(blank=True, default="", max_length=128, verbose_name="additional information"),
        ),
        migrations.AddField(
            model_name="referencepaymentbatchfile",
            name="msg_id",
            field=models.CharField(blank=True, db_index=True, default="", max_length=32, verbose_name="message identifier"),
        ),
        migrations.AddField(
            model_name="referencepaymentbatchfile",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True, verbose_name="timestamp"),
        ),
    ]
