# Generated by Django 4.1.7 on 2023-03-25 10:14

from django.db import migrations
from django.db.models import F


def migr25(apps, schema):
    ReferencePaymentBatchFile = apps.get_model("jbank", "ReferencePaymentBatchFile")
    ReferencePaymentBatchFile.objects.all().filter(timestamp=None).update(timestamp=F("created"))


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0024_referencepaymentbatchfile_additional_info_and_more"),
    ]

    operations = [
        migrations.RunPython(migr25),
    ]
