# Generated by Django 4.1.7 on 2023-03-27 04:13

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0025_auto_20230325_1014"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepaymentbatch",
            name="identifier",
            field=jutil.modelfields.SafeCharField(blank=True, max_length=32, verbose_name="institution"),
        ),
        migrations.AlterField(
            model_name="referencepaymentbatch",
            name="currency_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="EUR", max_length=3, verbose_name="currency"),
        ),
        migrations.AlterField(
            model_name="referencepaymentbatch",
            name="institution_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=2, verbose_name="institution"),
        ),
        migrations.AlterField(
            model_name="referencepaymentbatch",
            name="service_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=9, verbose_name="service"),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="record_type",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=1, verbose_name="record type"),
        ),
    ]
