# Generated by Django 4.1.7 on 2023-03-27 05:30

from django.db import migrations, models
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0027_referencepaymentrecord_value_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencepaymentrecord",
            name="creditor_bank_bic",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=16, verbose_name="creditor bank BIC"),
        ),
        migrations.AddField(
            model_name="referencepaymentrecord",
            name="end_to_end_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=128, verbose_name="end to end identifier"),
        ),
        migrations.AddField(
            model_name="referencepaymentrecord",
            name="instructed_amount",
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name="instructed amount"),
        ),
        migrations.AddField(
            model_name="referencepaymentrecord",
            name="instructed_currency",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=3, verbose_name="instructed currency"),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="correction_identifier",
            field=jutil.modelfields.SafeCharField(
                choices=[("0", "Regular Entry"), ("1", "Correction Entry")], default="", max_length=1, verbose_name="correction identifier"
            ),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="currency_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, choices=[("1", "EUR")], default="", max_length=1, verbose_name="currency identifier"),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="delivery_method",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[("", ""), ("A", "From Customer"), ("K", "From Bank Clerk"), ("J", "From Bank System")],
                db_index=True,
                default="",
                max_length=1,
                verbose_name="delivery method",
            ),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="name_source",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[("", "Not Set"), ("A", "From Customer"), ("K", "From Bank Clerk"), ("J", "From Bank System")],
                default="",
                max_length=1,
                verbose_name="name source",
            ),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="payer_name",
            field=jutil.modelfields.SafeCharField(blank=True, db_index=True, default="", max_length=64, verbose_name="payer name"),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="receipt_code",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[("", ""), ("0", "(0)"), ("E", "Separate"), ("P", "Separate/Paper")],
                db_index=True,
                default="",
                max_length=1,
                verbose_name="receipt code",
            ),
        ),
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="remittance_info",
            field=jutil.modelfields.SafeCharField(db_index=True, max_length=128, verbose_name="remittance info"),
        ),
    ]
