# Generated by Django 4.1.7 on 2023-03-27 06:07

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0028_referencepaymentrecord_creditor_bank_bic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="remittance_info",
            field=jutil.modelfields.SafeCharField(db_index=True, max_length=1024, verbose_name="remittance info"),
        ),
    ]
