# Generated by Django 4.1.7 on 2023-04-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0030_alter_referencepaymentrecord_remittance_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="old_encryption_key_file",
            field=models.FileField(blank=True, editable=False, upload_to="certs", verbose_name="old encryption key file"),
        ),
        migrations.AddField(
            model_name="wsediconnection",
            name="old_signing_key_file",
            field=models.FileField(blank=True, editable=False, upload_to="certs", verbose_name="old signing key file"),
        ),
    ]
