# Generated by Django 4.1.7 on 2023-04-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0031_wsediconnection_old_encryption_key_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="use_sha256",
            field=models.BooleanField(blank=True, default=False, verbose_name="SHA-256"),
        ),
    ]
