# Generated by Django 4.1.7 on 2023-05-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0032_wsediconnection_use_sha256"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="begin_date",
            field=models.DateField(blank=True, db_index=True, default=None, null=True, verbose_name="begin date"),
        ),
    ]
