# Generated by Django 4.1.7 on 2023-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0033_alter_statement_begin_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="use_wsse_timestamp",
            field=models.BooleanField(blank=True, default=False, verbose_name="Use WS-Security timestamp"),
        ),
    ]
