# Generated by Django 4.1.7 on 2023-08-15 22:48

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0034_wsediconnection_use_wsse_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="agreement_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=32, verbose_name="agreement identifier"),
        ),
        migrations.AddField(
            model_name="wsediconnection",
            name="signer_identifier",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=32, verbose_name="signer identifier"),
        ),
    ]
