# Generated by Django 4.1.7 on 2023-08-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0036_remove_referencepaymentrecord_manually_settled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencepaymentrecord",
            name="marked_reconciled",
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name="marked as reconciled"),
        ),
        migrations.AlterField(
            model_name="statementrecord",
            name="marked_reconciled",
            field=models.BooleanField(blank=True, db_index=True, default=False, verbose_name="marked as reconciled"),
        ),
    ]
