# Generated by Django 5.0 on 2024-11-12 05:38

import jutil.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0037_alter_referencepaymentrecord_marked_reconciled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payoutstatus",
            name="group_status",
            field=jutil.modelfields.SafeCharField(blank=True, db_index=True, max_length=8, verbose_name="payment.group.status"),
        ),
    ]
