# Generated by Django 5.0 on 2025-02-19 19:28

import jutil.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0039_alter_payout_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="state",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[
                    ("H", "on hold"),
                    ("W", "waiting processing"),
                    ("B", "waiting batch processing"),
                    ("U", "waiting upload"),
                    ("BU", "waiting batch upload"),
                    ("D", "uploaded"),
                    ("P", "paid"),
                    ("C", "canceled"),
                    ("E", "error"),
                ],
                db_index=True,
                default="W",
                max_length=2,
                verbose_name="state",
            ),
        ),
    ]
