# Generated by Django 5.0 on 2025-04-06 15:53

import jutil.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0040_alter_payout_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statementrecord",
            name="record_domain",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[
                    ("PMNT", "Money Transfer (In/Out)"),
                    ("LDAS", "Loan Payment (Out)"),
                    ("CAMT", "Cash Management"),
                    ("ACMT", "Account Management"),
                    ("XTND", "Entended Domain"),
                    ("SECU", "Securities"),
                    ("FORX", "Foreign Exchange"),
                    ("TRAD", "Trade Services"),
                    ("XTND", "Entended Domain"),
                    ("NTAV", "Not Available"),
                ],
                db_index=True,
                max_length=4,
                verbose_name="record domain",
            ),
        ),
    ]
