# Generated by Django 5.0 on 2025-04-22 13:57

import jutil.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0041_alter_statementrecord_record_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="end_to_end_id",
            field=jutil.modelfields.SafeCharField(blank=True, db_index=True, editable=False, max_length=64, verbose_name="end-to-end id"),
        ),
        migrations.AddField(
            model_name="payoutstatus",
            name="end_to_end_id",
            field=jutil.modelfields.SafeCharField(blank=True, db_index=True, max_length=64, verbose_name="end-to-end id"),
        ),
    ]
