# Generated by Django 5.2.8 on 2026-01-15 22:11

import jutil.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0042_payout_end_to_end_id_payoutstatus_end_to_end_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="state",
            field=jutil.modelfields.SafeCharField(
                blank=True,
                choices=[
                    ("H", "on hold"),
                    ("W", "waiting processing"),
                    ("B", "waiting batch processing"),
                    ("U", "waiting upload"),
                    ("BU", "waiting batch upload"),
                    ("D", "uploaded"),
                    ("P", "paid"),
                    ("C", "canceled"),
                    ("E", "error"),
                    ("WA", "waiting approval"),
                ],
                db_index=True,
                default="W",
                max_length=2,
                verbose_name="state",
            ),
        ),
    ]
