# Generated by Django 6.1.1 on 2026-09-23 20:38

import jutil.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0043_alter_payout_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutparty",
            name="notes",
            field=jutil.modelfields.SafeTextField(blank=True, default="", verbose_name="notes"),
        ),
        migrations.AddField(
            model_name="payoutparty",
            name="recipient_name_verified",
            field=models.BooleanField(default=False, verbose_name="recipient name verified"),
        ),
    ]
