# Generated by Django 6.1.1 on 2026-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0044_payoutparty_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutparty",
            name="recipient_name_verified",
        ),
        migrations.AddField(
            model_name="payoutparty",
            name="name_verified",
            field=models.BooleanField(default=False, verbose_name="name verified"),
        ),
    ]
