# Generated by Django 6.1.1 on 2026-09-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0045_remove_payoutparty_recipient_name_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payoutparty",
            name="name_verified",
        ),
        migrations.AddField(
            model_name="payoutparty",
            name="verification_of_payee",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "verification.of.payee.unknown"),
                    ("M", "verification.of.payee.match"),
                    ("P", "verification.of.payee.partial.match"),
                    ("N", "verification.of.payee.not.match"),
                ],
                default="",
                verbose_name="verification of payee",
            ),
        ),
    ]
