# Generated by Django 6.1.1 on 2026-09-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0047_alter_payoutparty_verification_of_payee"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutparty",
            name="archived",
            field=models.BooleanField(blank=True, db_index=True, default=False, editable=False, verbose_name="archived"),
        ),
    ]
