# Generated by Django 6.1.1 on 2026-09-24 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0048_payoutparty_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutparty",
            name="original",
            field=models.ForeignKey(
                blank=True,
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jbank.payoutparty",
                verbose_name="original",
            ),
        ),
    ]
