# Generated by Django 2.2.3 on 2019-11-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0051_payout_connection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="jbank.WsEdiConnection",
                verbose_name="WS-EDI connection",
            ),
        ),
    ]
