# Generated by Django 3.0.4 on 2020-03-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0058_auto_20200316_1949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="statement",
            name="bic",
            field=models.CharField(db_index=True, max_length=11, verbose_name="BIC"),
        ),
    ]
