# Generated by Django 3.0.4 on 2020-04-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0061_auto_20200325_2204"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutstatus",
            name="file_path",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, verbose_name="file path"),
        ),
        migrations.AlterField(
            model_name="payoutstatus",
            name="file_name",
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128, verbose_name="file name"),
        ),
    ]
