# Generated by Django 3.0.8 on 2020-07-17 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0064_auto_20200629_0344"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="bank_root_cert_file",
            field=models.FileField(blank=True, upload_to="certs", verbose_name="bank root certificate file"),
        ),
    ]
