# Generated by Django 3.0.8 on 2020-07-17 23:22

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("jbank", "0065_wsediconnection_bank_root_cert_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="pin",
            field=jutil.modelfields.SafeCharField(blank=True, default="", max_length=64, verbose_name="PIN"),
        ),
    ]
