# Generated by Django 3.0.8 on 2020-07-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0066_wsediconnection_pin"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="pki_endpoint",
            field=models.URLField(blank=True, default="", verbose_name="PKI endpoint"),
        ),
    ]
