# Generated by Django 3.0.8 on 2020-07-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0067_wsediconnection_pki_endpoint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wsediconnection",
            name="soap_endpoint",
            field=models.URLField(verbose_name="EDI endpoint"),
        ),
    ]
