# Generated by Django 3.0.8 on 2020-07-17 23:33

from django.db import migrations
import jutil.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0068_auto_20200717_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wsediconnection",
            name="debug_commands",
            field=jutil.modelfields.SafeTextField(
                blank=True, help_text="wsedi.connection.debug.commands.help.text", verbose_name="debug commands"
            ),
        ),
    ]
