# Generated by Django 3.0.8 on 2020-07-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0069_auto_20200717_2333"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="bank_signing_cert_file",
            field=models.FileField(blank=True, upload_to="certs", verbose_name="bank signing cert file"),
        ),
    ]
