# Generated by Django 3.0.8 on 2020-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jbank", "0070_wsediconnection_bank_signing_cert_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="wsediconnection",
            name="ca_cert_file",
            field=models.FileField(blank=True, upload_to="certs", verbose_name="CA certificate file"),
        ),
    ]
